### ISSUE TITLE
The Implementation of Guided Cost Learning

### ISSUE THREAD

**Issue by lkhit** [DanielTakeshi/Paper_Notes#1]
Dear Dr. Seita,

Thanks for your paper_notes. I am now working on an autonomous driving project based on GCL. However, I have no idea how to implement the GCL algorithm. I really want to implement the GCL algorithm,  I was wondering if you could provide some implementation code with me. Thank you.

Sincerely

**Comment by DanielTakeshi** [comment]
You should contact Chelsea Finn, the author of the paper.

I see this http://rll.berkeley.edu/gps/

Though that's guided *policy* search, but maybe there's something else online...
